# Generated by Django 3.2.7 on 2021-11-18 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PutPutApp', '0002_populate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
    ]
