# Generated by Django 3.2.7 on 2021-12-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PutPutApp', '0003_auto_20211118_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='par',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
