# Generated by Django 3.2.7 on 2021-11-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PutPutApp', '0005_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bartender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='player',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sponsor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Player', 'Player'), ('Bartender', 'Bartender'), ('Sponsor', 'Sponsor'), ('Manager', 'Manager')], max_length=30),
        ),
    ]
