# Generated by Django 3.2.7 on 2021-11-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PutPutApp', '0006_auto_20211109_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bartender',
            new_name='barkeep',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Player', 'Player'), ('Barkeep', 'Barkeep'), ('Sponsor', 'Sponsor'), ('Manager', 'Manager')], max_length=30),
        ),
    ]
