# Generated by Django 3.2.7 on 2021-11-16 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PutPutApp', '0007_auto_20211114_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('tournament_name', models.CharField(max_length=60)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PutPutApp.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Calandar',
        ),
    ]
