# Generated by Django 3.2.7 on 2021-11-16 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PutPutApp', '0008_auto_20211115_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='sponsor',
        ),
    ]
