# Generated by Django 3.2.7 on 2021-11-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PutPutApp', '0009_remove_calendar_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('tournament_name', models.CharField(max_length=60)),
            ],
        ),
    ]
