# Generated by Django 3.2.7 on 2021-11-17 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PutPutApp', '0010_sponsorrequest'),
        ('PutPutApp', '0020_populate'),
    ]

    operations = [
    ]
